// Generated by LiveScript 1.3.1
(function(){
  var request, readability;
  request = require('request');
  readability = require('readability');
  module.exports = {
    getReadableContent: function(url, cbk){
      return request(url, function(err, response, body){
        if (!err && response.statusCode === 200) {
          return readability.parse(body, url, function(result){
            return cbk(result);
          });
        }
      });
    },
    allowOrigin: function(req, resp){
      var headers;
      headers = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, GET, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Credentials': false,
        'Access-Control-Max-Age': '86400',
        'Access-Control-Allow-Headers': 'X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept'
      };
      resp.writeHead(200, headers);
      if (req.method === 'OPTIONS') {
        return resp.end();
      }
    }
  };
}).call(this);
