// Generated by LiveScript 1.3.1
(function(){
  var _returnJson, returnJson, returnErrorJson;
  _returnJson = function(resp, obj){
    var json;
    resp.writeHead(200, {
      'Content-Type': 'application/json;charset=UTF-8'
    });
    json = JSON.stringify(obj);
    resp.end(json);
  };
  returnJson = function(resp, data){
    _returnJson(resp, {
      status: 'success',
      data: data
    });
  };
  returnErrorJson = function(resp, message){
    message == null && (message = 'some error');
    _returnJson(resp, {
      status: 'error',
      message: message
    });
  };
  module.exports = {
    returnJson: returnJson,
    returnErrorJson: returnErrorJson
  };
}).call(this);
